-- 관리자 화면입니다.

CREATE TABLESPACE user6Ts
DATAFILE 'C:/bizwork/MyDB/user6Ts.dbf'
SIZE 100M AUTOEXTEND ON NEXT 100K;

CREATE USER user6
IDENTIFIED BY 1234
DEFAULT TABLESPACE user6Ts;

GRANT DBA TO user6;
